// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// symmetricPower_C
arma::mat symmetricPower_C(arma::mat x, double r);
RcppExport SEXP ICtest_symmetricPower_C(SEXP xSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(symmetricPower_C(x, r));
    return rcpp_result_gen;
END_RCPP
}
// computeObj_C
arma::vec computeObj_C(arma::mat x, arma::vec nl, arma::vec alpha);
RcppExport SEXP ICtest_computeObj_C(SEXP xSEXP, SEXP nlSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nl(nlSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(computeObj_C(x, nl, alpha));
    return rcpp_result_gen;
END_RCPP
}
// computeTVec_C
arma::vec computeTVec_C(arma::vec u, arma::mat x, arma::vec nl, arma::vec alpha);
RcppExport SEXP ICtest_computeTVec_C(SEXP uSEXP, SEXP xSEXP, SEXP nlSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type u(uSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type x(xSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type nl(nlSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(computeTVec_C(u, x, nl, alpha));
    return rcpp_result_gen;
END_RCPP
}
